// -*- mode: c++ -*-

// display = make_unique<window_property>();

// vector<status_ptr> items;

// items.push_back( make_unique<periodic>( make_unique<load_avg>(), seconds(5) ) );
// items.push_back( make_unique<periodic>( make_unique<mail_dir>(), seconds(90) ) );
// items.push_back( make_unique<periodic>( make_unique<cpu_temp>(), seconds(3) ) );
// items.push_back( make_unique<periodic>( make_unique<battery>(), seconds(5) ) );
// items.push_back( make_unique<unicode_time>() );

// status = make_unique<bar>( move(items), bar::default_sep, "", " " );
